### ISSUE TITLE
"connect-mongo" sessionStore "No session found"

### ISSUE THREAD

**Issue by cdagli** [jfromaniello/passport.socketio#100]
Hello, 

I am migrating socket.io from 0.9 to 1.3.5 but passport.socketio doesn't recognize the session from sessionStore "connect-mongo" and gives the below error. It was working okay with the 0.9 

 ```socket.io:client writing packet {"type":4,"data":"No session found","nsp":"/"} +1ms
 socket.io-parser encoding packet {"type":4,"data":"No session found","nsp":"/"} +1s
 socket.io-parser encoded {"type":4,"data":"No session found","nsp":"/"} as 4"No session found" +0ms```

I can see the session created in the mongoDB when I login to the app ;

 ```
{
    "_id" : "D9SgKPIChpbezzEMv8H2MYnJOgIhebKS",
    "session" : "{\"cookie\":{\"originalMaxAge\":251971839716212,\"expires\":\"9999-12-31T23:46:49.154Z\",\"httpOnly\":true,\"path\":\"/\"},\"passport\":{\"user\":\"54d61481de061f73229b750f\"}}",
    "expires" : Date(253402300063747)
}
 ```

And here is my code; 

server.js
 ```
var http = require('http').createServer(app).listen(port);;
var io = require("socket.io")(http);
var session      = require('express-session');
var configDB = require('./config/database.js');
var MongoStore = require('connect-mongo')(session);
var sessionStore = new MongoStore(configDB);
var passportSocketIo = require("passport.socketio");

//=============== passport.js start ==============
require('./config/passport')(passport); // pass passport for configuration
app.use(session({ secret: 'some secret',  
                  store: sessionStore,
 				          resave: false,
                  saveUninitialized: true })); // session secret
app.use(passport.initialize());
app.use(passport.session()); // persistent login sessions
//=============== passport.js end ==============

io.use(passportSocketIo.authorize({
  passport    : passport,
  cookieParser: cookieParser,       // the same middleware you registrer in express
  key:          'connect.sid',       // the name of the cookie where express/connect stores its session_id
  secret:       'some secret(same with the above',    // the session_secret to parse the cookie
  store:        sessionStore,        // we NEED to use a sessionstore. no memorystore please
  success:      onAuthorizeSuccess,  // *optional* callback on success - read more below
  fail:         onAuthorizeFail,     // *optional* callback on fail/error - read more below
}));

function onAuthorizeSuccess(data, accept){
  logger.info('successful connection to socket.io');
  // accept connection
  accept();

  // reject connection (for whatever reason)
  accept(new Error('optional reason'));
}

function onAuthorizeFail(data, message, error, accept){
  // error indicates whether the fail is due to an error or just a unauthorized client
  console.log("HATA HATA HATA" + data + error);
  if(error)  throw new Error(message);
  // send the (not-fatal) error-message to the client and deny the connection
  return accept(new Error(message));
} 
```



database.js


 ```
// config/database.js
module.exports = {
	'url' : 'mongodb://localhost:27017/atmadb' 
};
 ```

NPM Versions: 
 ```
  "name": "connect-mongo",
  "version": "0.8.1",

  "name": "socket.io",
  "version": "1.3.5",

  "name": "passport",
  "version": "0.2.1",

  "name": "passport.socketio",
  "version": "3.5.1",

  "name": "express",
  "version": "4.0.0",
 ```

When the sessionStore definition fails e.g. not configured, it fallbacks to memoryStore and it works like that. If I change the below line like that it gives the error but socket.io starts to work;

 ```
var sessionStore = new MongoStore();
 ```

 ```
error: uncaughtException: Cannot use 'in' operator to search for 'auto_reconnect
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +1ms
  socket.io:socket joining room CKhuLhgyQTgNPG9QAAAC +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +121ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
 ```

Everything else related to session works okay. So that's why I created the issue to passport.socketio.

Thank you

** Edit: Also tried with redis-store same thing happening; **

 ```
var RedisStore = require('connect-redis')(session);//require('connect-mongo')(session);
var sessionStore = new RedisStore({"host" : "127.0.0.1", "port" : "6379"});
 ```

Obviously I am doing wrong something fundamental.

**Comment by cdagli** [comment]
I've solved the issue and it was non related with the server side. 

If you use this library https://github.com/socketio/socket.io-client-swift don't forget to attach the cookies to the socket connect options. 

(The old one I am using was automatically adding it.) 

Issue can be closed.

**Comment by jfromaniello** [comment]
Cool!
