### ISSUE TITLE
Loguot method

### ISSUE THREAD

**Issue by retyui** [jfromaniello/passport.socketio#101]
If the user clicked to logout the site
session is destroyed, but there is no method that can be break the connection

**Comment by BlaM** [comment]
... and socket.request.logged_in remains to be true

Is there an official way to detect that the user has logged out (maybe even in another browser tab?)

**Comment by djskinner** [comment]
Did anyone ever find a solution to this?

In my app sockets are for authenticated users only. If they sign out the socket needs to be killed too.

**Comment by BlaM** [comment]
Is there a solution to this, yet?

**Comment by retyui** [comment]
No
