### ISSUE TITLE
fail callback syntax

### ISSUE THREAD

**Issue by DominicBoettger** [jfromaniello/passport.socketio#113]
It seems that in the combination with the latest passport/redis version the callback has changed

works:
fail: function(data, message, authenticated, accept) {

does not work anymore:
fail: function(data, accept) {

**Comment by jfromaniello** [comment]
The fail callback has this signature since we introduced it in this commit:

https://github.com/jfromaniello/passport.socketio/commit/928cd508ffe40c9ed7726a38131d917c6075cdc9

**Comment by DominicBoettger** [comment]
Okay, thanks. Saw it has also been changed in the docs.
