### ISSUE TITLE
Express 4

### ISSUE THREAD

**Issue by witoldsz** [jfromaniello/passport.socketio#63]
Hi,
I have just tried this in Express 4 environment and everything seems to be working fine. The README.md could mention about it, or does anyone have issues with Express 4?

P.S.
This is a nice trick with `parseCookie` function preparing faked `req` object. I couldn't find a way to extract session cookie. Thanks to `passport.socketio` my searches are over :)

**Comment by ant-fx** [comment]
@revir thx for that
