### ISSUE TITLE
How to test from node or how to use the same cookies for request and socket.io-client?

### ISSUE THREAD

**Issue by maziyarpanahi** [jfromaniello/passport.socketio#72]
Hi,

I am writing a little benchmark script to see how many users I can handle on the server. I use require('request').post to login (passport local strategy) and after I try io.connect to make a connection to Socket.io but I get this error: failed connection to socket.io: No session found.

Is there any way to pass the session with io.coonect? Because when I define var cookieJar = request.jar(); and pass it as a parameter in request.post I get the cookie. Is this kind of authentication possible at all?

(all the passport strategies are working fine. this module also works fine both in browsers and iOS app)

Thanks

**Comment by tirithen** [comment]
Anyone who got something similar working with socket.io-client 1.3.5? I seem no longer possible to hook in to the initial http request with this version.

**Comment by nathansherburn** [comment]
For others finding this thread, socket.io now allows you to send custom request headers in NodeJS like so:

```
var io = require('socket.io-client')

var socket = io('http://yourwebsite.com', {
  extraHeaders: {
    'Cookie': 'your-cookie_info_here'
  }
});
```
