### ISSUE TITLE
Request is not passed to passport.deserializeUser

### ISSUE THREAD

**Issue by morungos** [jfromaniello/passport.socketio#92]
The mocked request is passed to most of the passport code, but not all. It's not passed to deserializeUser, which means that arrives with a null request and none of its properties can be accessed. deserializeUser does accept a request argument, so it probably should be passed in for consistency. 

(Actually, i have a problem that goes deeper: I need the app property from the original request, but I can easily inject that myself -- if the request is passed back into the passport.)

**Comment by jfromaniello** [comment]
Thanks, this was fixed in 3.5.0 which includes the code in your PR
