### ISSUE TITLE
CORS Workaround with HttpOnly

### ISSUE THREAD

**Issue by grofit** [jfromaniello/passport.socketio#94]
I am not quite sure if this applies, but I currently use CORS and the cookie is issued from the web service which is on port 2000 and the client is on port 3000.

So client authenticates via http with CORS and gets a cookie which is for the web service on port 2000, I have setup Socket io to use CORS which it seems to do fine, so do I still need to do the CORS workaround? as I cannot read the cookie as it is httpOnly, but it *should* be valid as the socket io instance is on the 2000 server so the cookie should work fine right?

**Comment by elgubenis** [comment]
is your cookie domain *.something.tld?

**Comment by grofit** [comment]
I dont know why I raised this issue, it was a long time ago but everything is working fine so I assume whatever question I was asking was answered as "yes it works".

There was no domain in this case, well it was technically localhost but it was just varying ports (to simulate CORS).
