### ISSUE TITLE
Client side check if socket is rejected because of not being logged in?

### ISSUE THREAD

**Issue by hohl** [jfromaniello/passport.socketio#99]
At the moment just nothing happens if a user is not authenticated and socket connection can't get established on client side because of it not being authenticated. Is there anyway to catch the event that socket is rejected because of user not authenticated?

**Comment by jfromaniello** [comment]
Yes, check the event error, like in this test:

https://github.com/jfromaniello/passport.socketio/blob/master/test/authorizer.test.js#L22-L28

**Comment by hohl** [comment]
Thanks. I tried so already before, but didn't work for me. However since the test runs, my error must somewhere else. Sorry for wasting your time. Good project, keep it up!
